### ISSUE TITLE
can not build with xcode 4.6

### ISSUE THREAD

**Issue by boyxuper** [kivy/kivy-ios#33]
cannot build python [tools/build-python.sh] if including this file 

[tools/environment.sh]

i paste the useful part into [tools/build-python.sh], remove the include and it works

``` bash
try () {
        "$@" || exit -1
}

function deduplicate() {
        fn=$(basename $1)
        echo "== Trying to remove duplicate symbol in $1"
        try mkdir ddp
        try cd ddp
        try ar x $1
        try ar rc $fn *.o
        try ranlib $fn
        try mv -f $fn $1
        try cd ..
        try rm -rf ddp
}

export PYTHON_VERSION=2.7.1
export KIVYIOSROOT="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
export BUILDROOT="$KIVYIOSROOT/build"
export TMPROOT="$KIVYIOSROOT/tmp"
export DESTROOT="$KIVYIOSROOT/tmp/root"
export CACHEROOT="$KIVYIOSROOT/.cache"
```

issue also described in this thread:
https://groups.google.com/forum/?fromgroups=#!topic/kivy-users/QVxmxb5gV3g

thanks
