### PR TITLE
WIP: Update openssl and ffmpeg version to fix build issues

### PR DESCRIPTION
**Pull request by Zen-CODE**
This updates the openssl and ffmpeg recipes, mainly the fix the outdated entry point used by the current ffmpeg recipe.

Relates to this PR: https://github.com/kivy/kivy-ios/issues/552

Informed by this patch: https://www.github.com/kivy/python-for-android/tree/develop/pythonforandroid%2Frecipes%2Fffmpeg%2Fpatches%2Fconfigure.patch

### CODE REVIEW

**Comment by Zen-CODE** [comment]
I can confirm this works and builds successfully with Mac Catalina + XCode 11.2.1.
```
[DEBUG   ] New State: ffmpeg.install at 2020-10-31 11:34:39.107634
[DEBUG   ] New State: ffmpeg.build_all at 2020-10-31 11:34:39.110386
```

**Comment by Zen-CODE** [comment]
Trying to run the app, it generates the following error. 
```
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _getstr8 in libavformat.a(mpegts.o)
      _avcodec_decode_subtitle2 in libavcodec.a(decode.o)
     (maybe you meant: _SDL_iconv, _SDL_iconv_open , _SDL_iconv_string , _SDL_iconv_close )
  "_iconv_close", referenced from:
      _getstr8 in libavformat.a(mpegts.o)
      _avcodec_decode_subtitle2 in libavcodec.a(decode.o)
      _avcodec_open2 in libavcodec.a(utils.o)
     (maybe you meant: _SDL_iconv_close)
  "_iconv_open", referenced from:
      _getstr8 in libavformat.a(mpegts.o)
      _avcodec_decode_subtitle2 in libavcodec.a(decode.o)
      _avcodec_open2 in libavcodec.a(utils.o)
     (maybe you meant: _SDL_iconv_open)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Zen-CODE** [comment]
Version n3.4.8 - ERROR: openssl not found
Version n2.6.3 / n2.8.17 - STDOUT: Unknown option "--disable-x86asm".
Version v4.3.1 - Builds but running fails with:
Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(decode.o)
      _getstr8 in libavformat.a(mpegts.o)
     (maybe you meant: _SDL_iconv_open, _SDL_iconv , _SDL_iconv_string , _SDL_iconv_close )
  "_iconv_close", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(decode.o)
      _avcodec_open2 in libavcodec.a(utils.o)
      _getstr8 in libavformat.a(mpegts.o)
     (maybe you meant: _SDL_iconv_close)
  "_iconv_open", referenced from:
      _avcodec_decode_subtitle2 in libavcodec.a(decode.o)
      _avcodec_open2 in libavcodec.a(utils.o)
      _getstr8 in libavformat.a(mpegts.o)
     (maybe you meant: _SDL_iconv_open)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by Cheaterman** [comment]
@Zen-CODE sorry I never mentioned this - when I was fighting with Xcode 12, and I went back to Xcode 11 to get things working, I had to add "libiconv.tbd" (or something like that) to the list of "Frameworks" in the Xcode project - I did it in the GUI but I assume some automagic fix could be made in the Xcode project file?

**Comment by misl6** [comment]
@Zen-CODE I have an upcoming PR to get this one working on Xcode 12.2 + a demo app, meanwhile can you please upgrade also `hostopenssl` to `1.1.1g`?

**Comment by Zen-CODE** [comment]
You don't want to do that as part of this PR? Is there a reason for that?

**Comment by misl6** [comment]
> You don't want to do that as part of this PR? Is there a reason for that?

For the `hostopenssl` upgrade part it absolutely makes sense to have that in this PR.

The fixes that I made on the other upcoming PR are quite unrelated but at the same time also fixes an issue that was triggered while testing this PR, so I prefer to hold it separate for future maintenance.

**Comment by Zen-CODE** [comment]
Sure, makes sense. I'll prep and test that shortly...

**Comment by Zen-CODE** [comment]
@misl6 Merged those changes so you are unblocked asap. Let's hope it works 👍

**Comment by misl6** [comment]
@Zen-CODE 

With all the recent changes + #571 you should be able to run on both Simulator and real device a videoplayer demo app that uses ` ffmpeg4.3.1 + openssl1.1.1g` on top of __Xcode 12.2__

Just for reference, I created a simple demo app for demonstrating / testing it.
https://gist.github.com/misl6/a6752029e6589c1e4f5a0d9ab4529907

I'm able to run it on Simulator + a real device with the latest iOS version.

**Comment by Zen-CODE** [comment]
It still gives an "OpenSSL not found" when building with the existing ffmpeg (Testing on XCode 12.1 first). Please could you  change the version in the ffmpeg recipe to "n4.3.1" to fix that in this PR?

**Comment by dotrichard** [comment]
Thanks for creating an app to test with, but I can't get it running for love or money. It builds, but gives me the attached permissions error when I try to run. Lots of googling + experiment get me nowhere...Building touchtracer works fine though, and it does build so it's still an improvement as the older ffmpeg does not!

Screenshot 2020-12-09 at 21 51 19

**Review by dotrichard — APPROVED** [review]
Can confirm it fixes the build issues Xcode 11.2.1/Catalina
