### ISSUE TITLE
Unable to build with kivymd==2.0

### ISSUE THREAD

**Issue by mrwulff** [kivy/kivy-ios#897]
**Versions**

* Python : 3.11.6
* MacOS version :latest
* XCode Version :latest
* Cython version :latest

**Describe the bug**

```
"/Users/*/Library/Developer/CoreSimulator/Devices/*/data/Containers/Bundle/Application/*/test.app/lib/python3.11/site-packages/kivy/graphics/__init__.py", line 96, in <module>
from kivy.graphics.vertex_instructions import Bezier, BorderImage, Ellipse, \
 ImportError: cannot import name 'SmoothRectangle' from 'kivy_graphics_vertex_instructions' (kivy_graphics_vertex_instructions)
```

**To Reproduce**
build latest, pip install kivymd,run any kivymd examples

**
