### ISSUE TITLE
Kivy 3.0 iOS catch-up: bump SDL3_mixer pin, add packaging to hostpython prereqs, default kivy recipe version, bump Cython, propagate USE_SDL3 to setup.py

### ISSUE THREAD

**Issue by ElliotGarbus** [kivy/kivy-ios#998]
## Summary

While bringing up Kivy 3.0 (`feature/video-avfoundation` from kivy/kivy)
under kivy-ios `master` (currently HEAD, validated at SHA `54426ed`),
five items surface that prevent a green `toolchain build kivy` against
a Kivy 3.0 source checkout: four small recipe-level gaps in kivy-ios
(items 1–4), plus one upstream Kivy `setup.py` fix included for
maintainer visibility (item 5, no kivy-ios action required). The
SDL3/ANGLE infrastructure introduced by #961 / #928 / #976 is correct
and works; the missing pieces are all small follow-ons.

## Environment

- macOS 14.8 (Darwin 23.6.0)
- Xcode 16.x with iPhoneOS 18.2 SDK
- Python 3.13 host venv, kivy-ios `master` @ `54426ed`
- Target source: kivy/kivy `feature/video-avfoundation`
  (Kivy 3.0.0.dev0), invoked via `KIVY_DIR=...`
- SDL3 stack already built (`angle`, `sdl3`, `sdl3_image`, `sdl3_ttf`,
  `sdl3_mixer` all complete OK)

### 1. `sdl3_mixer` recipe pins a pre-3.0-stable snapshot

**File**: `kivy_ios/recipes/sdl3_mixer/__init__.py`
**Pin**: `version = "78a2035cf4cf95066d7d9e6208e99507376409a7"`

This SHA predates SDL_mixer 3.0's stable release (Mar 9, 2025), which
introduced the new `MIX_*` namespace (`MIX_Mixer`, `MIX_Audio`,
`MIX_Track`, `MIX_LoadAudio`, `MIX_CreateMixerDevice`, `MIX_Init`,
...) replacing the legacy SDL2-derived `Mix_*` names. Kivy 3.0's
`kivy/lib/sdl3.pxi` is written against the new API.

The installed header (built from `78a2035`) still exposes only the
legacy names:

```
$ rg 'MIX_Init|MIX_LoadAudio|MIX_Mixer' dist/include/common/sdl3_mixer/SDL3_mixer/SDL_mixer.h
75:typedef Uint32 MIX_InitFlags;
152:extern SDL_DECLSPEC MIX_InitFlags SDLCALL Mix_Init(MIX_InitFlags flags);
```

`MIX_InitFlags` is the only `MIX_*` symbol; everything else is `Mix_*`.

When `setup.py build_ext` cythonizes `kivy/core/audio_output/audio_sdl3.pyx`
and clang compiles the generated C, this happens:

```
audio_sdl3.c:1560:3: error: unknown type name 'MIX_Audio'
audio_sdl3.c:2264:8: error: unknown type name 'MIX_Mixer'
audio_sdl3.c:3561:10: error: call to undeclared function 'MIX_Init'; did you mean 'Mix_Init'?
SDL_mixer.h:152: note: 'Mix_Init' declared here
audio_sdl3.c:3789:25: error: call to undeclared function 'MIX_CreateTrack'; did you mean 'SDL_CreateTray'?
... 20 errors, fatal error: too many errors emitted, stopping now
```

(`MIX_CreateTrack`/`MIX_DestroyTrack` aren't even in the header so
clang's "did you mean" suggests `SDL_CreateTray`/`SDL_DestroyTray`.)

**Suggested fix**: bump `version` to a stable SDL_mixer 3.x release —
e.g. `3.0.0` (Mar 9, 2025) or the latest stable `3.1.0` (May 11, 2026).
Mirrors what #980/#983 did for SDL3 and SDL3_ttf, but for SDL3_mixer.

### 2. `KivyRecipe.version` still pinned to `2.3.1`

**File**: `kivy_ios/recipes/kivy/__init__.py`
**Pin**: `version = "2.3.1"`

`get_required_sdl_version()` (introduced in #976) downloads `kivy.zip`
for `self.version` and runs `python -c "import _version"` against the
extracted tree to read `__version__`. With `version = "2.3.1"`, the
probe parses `2.3.1 < 3.0.0.dev0`, returns `"sdl2"`, and the rest of
the recipe (`pbx_frameworks`, `depends`, `get_recipe_env`) selects
the SDL2 stack — **even when the user is supplying a Kivy 3.0
checkout via `KIVY_DIR`.**

This silently produces an SDL2 build that will fail at link time (or
later) because the local source actually requires SDL3+ANGLE.

**Suggested fix (preferred)**: when `self.custom_dir` is set, run the
`_version.py` probe against `custom_dir/kivy/_version.py` directly,
instead of always downloading `self.version`. The probe should
already prefer the user's actual source. Pseudocode:

```python
def get_required_sdl_version(self):
    if self._required_sdl_version is not None:
        return self._required_sdl_version
    kivy_dir = self.custom_dir or self._download_and_extract_version()
    version_str = subprocess.check_output(
        [sys.executable, "-c", "import _version; print(_version.__version__)"],
        cwd=join(kivy_dir, "kivy"),
    ).decode().strip()
    kv = packaging.version.parse(version_str)
    self._required_sdl_version = (
        "sdl2" if kv < packaging.version.parse("3.0.0.dev0") else "sdl3"
    )
    return self._required_sdl_version
```

**Future fix (after Kivy 3.0 ships a release tag)**: bump the default
`version` to that Kivy 3.0 tag, so the SDL3 path becomes the
out-of-the-box default. Not actionable now since Kivy 3.0 is still
`3.0.0.dev0`.

### 3. `KivyRecipe.hostpython_prerequisites` missing `packaging`

**File**: `kivy_ios/recipes/kivy/__init__.py`

`KivyRecipe` doesn't override `hostpython_prerequisites`; it inherits
`["Cython==3.0.11"]` from `CythonRecipe`. Kivy 3.0's `setup.py` does
`from packaging import version` at module top (used for Cython
version gating around line 462 of `setup.py`). Result:

```
$ toolchain build kivy
...
ModuleNotFoundError: No module named 'packaging'
sh.ErrorReturnCode_1: ... setup.py build_ext -g
```

**Suggested fix**: one-line addition.

```python
class KivyRecipe(CythonRecipe):
    ...
    hostpython_prerequisites = ["Cython==3.0.11", "packaging"]
```

### 4. Cython pin (`3.0.11`) rejects valid bindings that Cython 3.2.x accepts

**File**: `kivy_ios/toolchain.py` (or wherever `Cython==3.0.11` is pinned)

Kivy 3.0's `kivy/lib/sdl3.pxi:956` originally had a typo (`bool`
instead of `bint`) in the `MIX_LoadAudio` cdef. Cython 3.2.x silently
accepts it; Cython 3.0.x rejects with:

```
kivy/lib/sdl3.pxi:956:71: 'bool' is not a type identifier
```

We've sent a fix to Kivy (use `bint`, matches the surrounding
functions in the same `cdef extern` block) so this specific symptom
is resolved upstream. But Cython 3.0.x being one minor version behind
the development tip is a general fragility — every Kivy 3.x release
will be developed against Cython 3.2+ and may pick up syntax/grammar
that 3.0.x rejects.

**Suggested fix**: bump the Cython pin to `Cython>=3.1` or pin to a
current 3.2.x. 

### 5. Upstream Kivy: `setup.py` doesn't auto-enable `use_sdl3` under kivy-ios cross-compile

**No kivy-ios action needed for this item** — included for visibility
since the symptom surfaces during the same `toolchain build kivy`
run. The fix belongs in kivy/kivy and will be sent as a separate
upstream PR.

**File** (in Kivy): `kivy/setup.py`

The auto-enable block (around line 340) only fires when
`sys.platform == 'ios'`. When kivy-ios cross-compiles using a macOS
host Python, `sys.platform == 'darwin'`, and `use_sdl3` falls back to
a `/Library/Frameworks/SDL3.framework` probe that has nothing to do
with the kivy-ios `<dist>/include/common/sdl3/` stack. The actual
`KIVY_SDL3_PATH` the recipe sets is ignored.

Local workaround in our recipe (to be removed once the Kivy fix lands):

```python
def get_recipe_env(self, plat):
    env = super().get_recipe_env(plat)
    env["USE_SDL3"] = "1"
    env["USE_OSX_FRAMEWORKS"] = "0"
    return env
```

**Upstream Kivy fix**: relax `setup.py`'s `use_sdl3` auto-detection
to honor `KIVY_SDL3_PATH` even when `sys.platform == 'darwin'`, and
ensure `KIVY_SDL3_PATH` overrides the `use_osx_frameworks`
`/Library/Frameworks/SDL3.framework` probe. Once that lands, the
local env-var workaround above can be deleted with no kivy-ios
changes required.

## Reproduction

To reproduce items 1–4 verbatim:

```bash
# Build SDL3 stack first (these work fine).
toolchain build angle sdl3 sdl3_image sdl3_ttf sdl3_mixer

# Then try to build Kivy 3.0 from a local checkout.
KIVY_DIR=/path/to/kivy-3.0-checkout toolchain build kivy
```

You'll hit (in order, after each individual fix):
1. `ModuleNotFoundError: No module named 'packaging'` (item 3)
2. Cython error on `sdl3.pxi:956` (item 4 — manifests if you have
   the pre-`bint`-fix Kivy source)
3. `unknown type name 'MIX_Audio'` from clang (item 1)
4. Silent SDL2 selection if you don't override `_required_sdl_version`
   (item 2)

## References

Related prior work: #961 #928 #976 #980 #983.

**Comment by ElliotGarbus** [comment]
Upstream Kivy issue filed for item 5: kivy/kivy#9316. Tracking the `setup.py` `use_sdl3` / `KIVY_SDL3_PATH` detection fix there. Once that lands, the `USE_SDL3=1` / `USE_OSX_FRAMEWORKS=0` workaround can be dropped without any kivy-ios changes.

**Comment by ElliotGarbus** [comment]
## Phase 2 follow-up: items 6–15 (iOS app bringup)

After applying local-recipe workarounds for items 1–4 above and getting
`toolchain build kivy` green against Kivy 3.0
(`feature/video-avfoundation`), I moved on to actually generating an
Xcode project (`toolchain create HelloIOS …`) and shipping it onto
the simulator. Ten more issues surfaced. None of these affect the
recipe build itself; they're all in the layer that turns the built
distribution into a runnable app — recipe link/embed flags, the
cookiecutter project template, and `update_pbxproj` hygiene.

All paths below are relative to `kivy_ios/` in `kivy-ios@54426ed`.
Verified against the cookiecutter template files in the installed
package and the runtime errors from a fresh `toolchain create`
project. Grouped by severity.

### Framing assumption: SDL2 is sunsetting

Items 8, 9, and 13 below are written assuming kivy-ios drops SDL2
when it cuts its first Kivy 3.0-supporting release (as foreshadowed
by the cookiecutter comment `// WIP_ Will move to angle and sdl3 as
default in the future`). Concretely: the current
`kivy-ios==2025.5.17` PyPI release is the sunset line for the
Kivy 2.x + SDL2 stack — Kivy 2.x users who need iOS pin to that
release (or any of the existing date-stamped releases). Master
drops `sdl2`, `sdl2_image`, `sdl2_mixer`, and `sdl2_ttf` entirely
in the same release that adds first-class Kivy 3.0 support.
This matches the precedent python-for-android set when it dropped
Python 2.

Under that assumption, the simplest fix for items 8/9/13 is "delete
SDL2 hardcodes / SDL2 paths", not "branch on
`KivyRecipe.get_required_sdl_version()`". If the maintainers prefer
to keep both SDL stacks in master long-term, those three items need
to be reframed as version-aware branching work (which is several
times the implementation effort). Happy to redraft if that's the
preferred direction.

---

### Hard blockers — nothing in the SDL3+ANGLE path builds or launches without these

#### 6. `angle` recipe is missing `pbx_libraries = ["libc++"]`

**File**: `recipes/angle/__init__.py`

`ANGLERecipe` declares neither `pbx_libraries` nor `pbx_frameworks`.
ANGLE's `libGLESv2` is C++ and depends on the C++ standard library
(`std::mutex`, `operator new`/`delete`, `___gxx_personality_v0` for
unwinding). On the legacy SDL2 path the link succeeded only because
`recipes/sdl2_mixer/__init__.py` happens to declare
`pbx_libraries = ["libc++"]` — nothing in the SDL3 / ANGLE recipes
does. As soon as you build a project without `sdl2_mixer`
(i.e. the SDL3 path), the final Xcode link fails:

```
Undefined symbol: std::__1::mutex::lock()
Undefined symbol: std::__1::mutex::unlock()
Undefined symbol: std::__1::mutex::~mutex()
Undefined symbol: operator delete(void*)
Undefined symbol: operator new(unsigned long)
Undefined symbol: ___gxx_personality_v0
Linker command failed with exit code 1
```

**Suggested fix**: declare `pbx_libraries = ["libc++"]` on the
`angle` recipe (or, alternatively, on `sdl3` — but `angle` is the
actual C++ consumer, so it's the least surprising owner).

```python
class ANGLERecipe(Recipe):
    version = "chromium-7151_rev1"
    url = "..."
    include_dir = ["include"]
    libraries = ["libEGL.a", "libGLESv2.a"]
    pbx_libraries = ["libc++"]   # <-- add this
```

#### 7. `angle` recipe ships dynamic xcframeworks but doesn't declare `embed_xcframeworks`

**File**: `recipes/angle/__init__.py`

`ANGLERecipe.install()` copies every `*.xcframework` it finds in the
build directory into `dist/xcframework/`. In practice that's
`libEGL.xcframework` and `libGLESv2.xcframework`, and the frameworks
inside them are **dynamic**:

```
$ file dist/xcframework/libGLESv2.xcframework/ios-arm64/libGLESv2.framework/libGLESv2
Mach-O 64-bit dynamically linked shared library arm64
```

But the recipe doesn't declare `embed_xcframeworks`, so
`update_pbxproj` adds them with `embed_framework=False`. The
generated project links them but does **not** embed them. Result:
every app built with the recipe crashes at launch.

```
DYLD 1 Library missing: @rpath/libGLESv2.framework/libGLESv2
Referenced from: <…>/helloios.app/helloios
dyld[…]: Library not loaded: @rpath/libGLESv2.framework/libGLESv2
```

Manual fix today is the Xcode UI: select both xcframeworks in
"Frameworks, Libraries, and Embedded Content" and switch
"Embed" → "Embed & Sign". The recipe should do that automatically.

**Suggested fix**: declare both names so `update_pbxproj` flags them
for embedding (mirroring how `sdl3` declares `embed_xcframeworks = ["SDL3"]`):

```python
class ANGLERecipe(Recipe):
    ...
    embed_xcframeworks = ["libEGL", "libGLESv2"]
```

(The recipe still also declares `libraries = ["libEGL.a", "libGLESv2.a"]`
which is inconsistent with the dynamic xcframeworks it actually ships —
the `.a` files don't exist in the prebuilt tarball and `install_libraries`
is silently a no-op. Worth a follow-up cleanup, but not urgent.)

---

### Cookiecutter template — SDL2 hardcodes need to flip to SDL3 + ANGLE

#### 8. `main.m` template hardcodes SDL2 — switch to SDL3 + ANGLE defaults

**File**: `tools/templates/{{ cookiecutter.project_name }}-ios/main.m`

Two hardcoded SDL2 sections:

```objective-c
// Line 9:
#include "{{ cookiecutter.dist_dir }}/include/common/sdl2/SDL_main.h"

// Lines 36-39:
putenv("KIVY_WINDOW=sdl2");
putenv("KIVY_IMAGE=imageio,tex,gif,sdl2");
putenv("KIVY_AUDIO=sdl2");
putenv("KIVY_GL_BACKEND=sdl2");
```

The comment on line 42 already acknowledges the direction
(`// WIP_ Will move to angle and sdl3 as default in the future`).
Today, every project generated by `toolchain create` against an
SDL3-only `dist/` ships dead-on-arrival:

* Build failure: `'…/include/common/sdl2/SDL_main.h' file not found`
  if SDL2 was never built or has been cleaned out.
* Even with the include patched out, the app crashes at launch:
  ```
  RuntimeError: Application didn't initialize properly,
  did you include SDL_main.h in the file containing your main() function?
  ```
  SDL3's iOS entry point is `SDL_main` and only gets set up when
  `<SDL3/SDL_main.h>` is included — without it, SDL never wires up
  `UIApplicationMain` and bootstraps the SDL3 lifecycle.
* The SDL2 env vars then send Kivy hunting for
  `kivy.core.window.window_sdl2` etc., which don't exist in any
  Kivy 3 build.

**Suggested fix** (post-SDL2-sunset framing): replace the SDL2
hardcodes with their SDL3+ANGLE equivalents in the template
directly. Verified working with Kivy 3.0 + ANGLE on the simulator:

```objective-c
// Replace line 9:
#include <SDL3/SDL_main.h>

// Replace lines 36-39:
putenv("KIVY_WINDOW=sdl3");
putenv("KIVY_IMAGE=imageio,tex,sdl3");
putenv("KIVY_AUDIO=avplayer");       // audio_sdl3 isn't buildable
                                     // until item 1 above lands; avplayer
                                     // (AVAudioPlayer) is iOS-native anyway
putenv("KIVY_GL_BACKEND=angle");

// Delete lines 41-43 (the WIP_ comment block — no longer WIP)
```

The `// WIP_ Will move to angle and sdl3 as default in the future`
comment block can be deleted in the same patch.

#### 9. `project.pbxproj` template hardcodes `dist/include/common/sdl2` in `HEADER_SEARCH_PATHS`

**File**: `tools/templates/{{ cookiecutter.project_name }}-ios/{{ cookiecutter.project_name }}.xcodeproj/project.pbxproj`

Both Debug and Release configs (lines ~256 and ~292) hardcode the
SDL2 header path:

```
HEADER_SEARCH_PATHS = (
    "{{ cookiecutter.dist_dir }}/root/python3/include/python3.11/**",
    "{{ cookiecutter.dist_dir }}/include/common/sdl2",
);
```

Same root cause as item 8 — without the matching SDL3 header path,
the `#include <SDL3/SDL_main.h>` from item 8 doesn't resolve and
the build dies at the preprocessor stage. Today the SDL3 path
requires hand-editing both occurrences of the generated
`project.pbxproj` after every `toolchain create`.

**Suggested fix** (post-SDL2-sunset framing): change `sdl2` →
`sdl3` in both `HEADER_SEARCH_PATHS` entries of the template:

```diff
 HEADER_SEARCH_PATHS = (
     "{{ cookiecutter.dist_dir }}/root/python3/include/python3.11/**",
-    "{{ cookiecutter.dist_dir }}/include/common/sdl2",
+    "{{ cookiecutter.dist_dir }}/include/common/sdl3",
 );
```

Two-line diff, applied to both Debug (line 256) and Release (line
292) configs.

---

### Cookiecutter template — missing modern keys / deprecated APIs

#### 10. `Info.plist` template missing `UIApplicationSupportsIndirectInputEvents`

**File**: `tools/templates/{{ cookiecutter.project_name }}-ios/{{ cookiecutter.project_name }}-Info.plist`

SDL3 logs a notice on every launch:

```
You need UIApplicationSupportsIndirectInputEvents in your Info.plist
for mouse support
```

The notice itself is cosmetic on iPhone, but the underlying behavior
is real: without this key, iPad trackpad/mouse and Apple-Silicon-Mac
"Designed for iPad" mouse input are silently disabled. The key has
been recommended by Apple since iOS 13.4 (Mar 2020).

**Suggested fix**: one-key addition to the cookiecutter Info.plist:

```xml
<key>UIApplicationSupportsIndirectInputEvents</key>
<true/>
```

#### 11. `main.m` template uses Python 3.11-deprecated APIs

**File**: `tools/templates/{{ cookiecutter.project_name }}-ios/main.m`

Lines 71 and 74:

```objective-c
PySys_SetArgv(argc, python_argv);   // deprecated, removed in 3.13
...
PyEval_InitThreads();               // no-op since 3.7, deprecated 3.9, removed 3.13
```

Both fire deprecation warnings on the current Python 3.11.6 we ship,
and both are scheduled for removal. Once `kivy-ios` bumps the Python
recipe past 3.12 these become hard build errors.

**Suggested fix**: migrate to the `PyConfig`-based initialization
path:

```objective-c
PyStatus status;
PyConfig config;
PyConfig_InitPythonConfig(&config);

PyConfig_SetBytesArgv(&config, argc, argv);
// (set program_name, isolated mode, home, etc. via PyConfig fields)

status = Py_InitializeFromConfig(&config);
PyConfig_Clear(&config);
if (PyStatus_Exception(status)) {
    Py_ExitStatusException(status);
}
```

And drop the `PyEval_InitThreads()` call entirely — it's been a no-op
since 3.7.

#### 12. `main.m` template uses the `imp` module (removed in Python 3.12)

**File**: `tools/templates/{{ cookiecutter.project_name }}-ios/main.m`

`load_custom_builtin_importer()` (lines 139–195) compiles a Python
string that does `import sys, imp, types` and uses `imp.load_dynamic`:

```python
"import sys, imp, types\n" \
...
"        try:\n" \
"            mod = imp.load_dynamic(f, f)\n" \
"        except ImportError:\n" \
"            mod = imp.load_dynamic(fullname, fullname)\n" \
```

Current Python 3.11.6 prints a `DeprecationWarning` on every launch:

```
<string>:1: DeprecationWarning: the imp module is deprecated in favour
of importlib and slated for removal in Python 3.12; see the module's
documentation for alternative uses
```

`imp` was **removed** in Python 3.12. The instant `kivy-ios` bumps
the Python recipe past 3.11, every generated app hard-fails at
startup with `ModuleNotFoundError: No module named 'imp'`.

**Suggested fix**: rewrite the custom importer to use
`importlib.util.spec_from_file_location` + `importlib.util.module_from_spec`:

```python
import sys, importlib.util, types
...
class CustomBuiltinImporter:
    def find_module(self, fullname, mpath=None):
        # unchanged
        ...
    def load_module(self, fullname):
        f = fullname.replace('.', '_')
        if f in sys.modules:
            return sys.modules[f]
        spec = importlib.util.spec_from_file_location(f, f)
        if spec is None:
            spec = importlib.util.spec_from_file_location(fullname, fullname)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        sys.modules[fullname] = mod
        return mod
```

Items 11 and 12 are good to land together as a single "modernize
`main.m` for Python 3.12+" PR.

---

### Toolchain hygiene — install and project-update assume monotonic `dist/` growth

#### 13. `update_pbxproj` iterates **every** `<recipe>.build_all` recipe in `ctx.state`, not the dep closure of the project

**File**: `toolchain.py:1316-1410` (`update_pbxproj`)

```python
def update_pbxproj(filename, pbx_frameworks=None):
    ctx = Context()
    ...
    for recipe in Recipe.list_recipes():
        key = "{}.build_all".format(recipe)
        if key not in ctx.state:
            continue
        recipe = Recipe.get_recipe(recipe, ctx)
        ...
        pbx_frameworks.extend(recipe.pbx_frameworks)
        pbx_libraries.extend(recipe.pbx_libraries)
        xcframeworks.extend(recipe.dist_xcframeworks)
        ...
```

Anything that has ever been built into the current `dist/` (i.e. has
a `<recipe>.build_all` key in `state.db`) gets wired into every
project, whether that project actually depends on it or not.

The most visible symptom — and the one that made this item painful
during my bringup — was the SDL2/SDL3 collision. If a user built
Kivy 2.3.1 first and then later rebuilt against Kivy 3.0, both
`libSDL2.xcframework` and `SDL3.xcframework` ended up in the
project. Since SDL2 and SDL3 share Objective-C class names
(`SDLUIKitDelegate`, `SDLInterruptionListener`,
`SDLUIKitOpenGLView`, …), every launch logs:

```
objc[17155]: Class SDLInterruptionListener is implemented in both
  …/SDL3.framework/SDL3 (0x1132551e8) and
  …/helloios.app/helloios (0x1106771d0).
  One of the two will be used. Which one is undefined.
```

…for every shared class, with genuinely undefined behavior (I hit
both freezes in `SDL_AppInit` and missing-symbol crashes depending
on link order). The only workaround was to `toolchain clean sdl2
sdl2_image sdl2_mixer sdl2_ttf` first, then regenerate the project.

**That specific symptom disappears once SDL2 is dropped from master**
— there's no SDL2 recipe left to collide. But the underlying
architectural bug remains: `update_pbxproj` makes projects fatter
than they should be, links recipes the app doesn't import, and turns
any future "two coexisting recipes that touch the same ObjC/symbol
namespace" footgun latent rather than active. (Plausible future
cases: two video backends, two audio backends, two image codec
recipes, a future SDL3 → SDL4 transition.)

**Suggested fix**: iterate the transitive dependency closure of the
project's actual top-level recipes — passed as CLI args to
`toolchain create` / `update`, or derived from the kivy recipe's
`depends` — instead of `Recipe.list_recipes()`. Recipes that were
built but aren't dependencies of the project shouldn't be wired
into its `project.pbxproj`. This is cleanup work, not a hard blocker
once SDL2 is gone, but it's the right architectural model.

#### 14. `PythonRecipe.install` does not wipe `site-packages` before reinstalling

**File**: `toolchain.py:1113-1145`

```python
class PythonRecipe(Recipe):
    @cache_execution
    def install(self):
        self.install_python_package()
        self.reduce_python_package()
        remove_junk(self.ctx.site_packages_dir)

    def install_python_package(self, ...):
        ...
        shprint(
            hostpython,
            "setup.py",
            "install",
            "-O2",
            "--root", self.ctx.python_prefix,
            "--prefix", "",
            _env=env,
        )
```

`setup.py install --root … --prefix ""` is overlay-only — setuptools
doesn't remove files that no longer exist in the new build. When the
file set legitimately *shrinks* across versions, the old files stay
forever. For Kivy 2.3.1 → 3.0 the difference is large:

| Removed in Kivy 3.0 | Stale file left over in `site-packages/kivy/` |
|---|---|
| `kivy/lib/sdl2.pxi` (replaced by `sdl3.pxi`) | `lib/sdl2.cpython-311-…-darwin.so` |
| `kivy/core/audio/audio_sdl2.pyx`             | `core/audio/audio_sdl2.cpython-311-…-darwin.so` |
| `kivy/core/image/img_sdl2.pyx`               | `core/image/img_sdl2.cpython-311-…-darwin.so` |
| `kivy/core/text/text_sdl2.pyx`               | `core/text/text_sdl2.cpython-311-…-darwin.so` |
| `kivy/core/window/window_sdl2.pyx`           | `core/window/window_sdl2.cpython-311-…-darwin.so` |
| `kivy/graphics/cgl_backend/cgl_sdl2.pyx`     | `graphics/cgl_backend/cgl_sdl2.cpython-311-…-darwin.so` |
| `kivy/core/audio_output/` (new dir in 3.0)   | n/a — but old `core/audio/` provider files persist |

The stale `.so` files dynamically link against `libSDL2` (which is
gone), get auto-discovered by Kivy's provider loader, and import-fail
in confusing ways at runtime — or, worse, get *linked into the final
app* via `update_pbxproj` (see item 13 above) and cause class
duplication.

**Suggested fix**: in `PythonRecipe.install`, wipe the recipe's own
subtree (e.g. `site_packages_dir/<self.name>/`) before
`install_python_package()`. Or pass `--single-version-externally-managed
--no-deps` and clean manually. Either way the install should be
idempotent against major-version downgrades.

#### 15. `toolchain create` and `toolchain update` don't accept `--add-custom-recipe`

**File**: `toolchain.py:1583-1638`

```python
def create(self):
    parser = argparse.ArgumentParser(...)
    parser.add_argument("name", ...)
    parser.add_argument("directory", ...)
    parser.add_argument("--add-framework", action="append", ...)
    args = parser.parse_args(sys.argv[2:])
    ...
    update_pbxproj(filename, pbx_frameworks=args.add_framework)

def update(self):
    parser = argparse.ArgumentParser(...)
    parser.add_argument("filename", ...)
    parser.add_argument("--add-framework", action="append", ...)
    args = parser.parse_args(sys.argv[2:])
    ...
    update_pbxproj(filename, pbx_frameworks=args.add_framework)
```

`build` and `clean` both take `--add-custom-recipe` (lines 1477-1478
and 1547-1548) and call `validate_custom_recipe_paths(ctx, ...)`.
`create` and `update` don't. So:

* A user with a custom recipe override (e.g. patching `KivyRecipe.pbx_libraries`
  to add `libc++` per item 6) can `toolchain build kivy
  --add-custom-recipe ~/my_recipes` and the build sees the override,
  **but** the moment they run `toolchain create MyApp …` the
  cookiecutter and `update_pbxproj` run against the stock recipe set
  — the override is invisible.
* End result: custom recipe overrides to `pbx_libraries`,
  `pbx_frameworks`, `embed_xcframeworks`, or `frameworks` have **no
  effect** on generated Xcode projects today. The only way to use a
  custom recipe is to hand-edit the resulting `project.pbxproj`.

**Suggested fix**: add `--add-custom-recipe` (and the corresponding
`validate_custom_recipe_paths` call) to `create` and `update`,
matching the pattern from `build` and `clean`.

---

### Cross-references and natural PR groupings

* **Items 6 + 7** — both `angle` recipe; combine into one small PR.
  Item 6 manifests during link, item 7 at launch; with both fixed
  the SDL3+ANGLE app stack works without any Xcode UI edits.
* **Items 8 + 9** — one PR ("modernize cookiecutter for SDL3 +
  ANGLE defaults"). Both are 1–2 line edits under the SDL2-sunset
  assumption; they're tightly coupled because the `#include <SDL3/SDL_main.h>`
  in item 8 doesn't resolve without the `common/sdl3` header path
  from item 9.
* **Items 11 + 12** — one PR ("modernize `main.m` Python init for
  3.12+"). Drop `PySys_SetArgv` and `PyEval_InitThreads`, replace
  `imp` with `importlib`. Same file, related rationale.
* **Item 14** — addresses the broader install hygiene issue that
  bit me during the Kivy 2→3 transition (stale `*sdl2*.so` files
  in `site-packages`). Worth fixing independently even with SDL2
  dropped, because every future Kivy major-version bump will
  shrink/rearrange the providers list.
* **Item 13** — independent. The acute SDL2/SDL3 class collision
  symptom disappears once SDL2 is dropped, but the underlying
  "links everything ever built" architectural issue stays — worth
  fixing for project hygiene and to prevent future recurrences.
* **Item 15** — quality-of-life follow-on for anyone wanting to
  ship custom recipes with custom `pbx_libraries` / `pbx_frameworks`
  / `embed_xcframeworks` overrides. Today those overrides are silently
  ignored by `toolchain create` / `update`.

### Priority

* **P0 — hard blockers, no SDL3 app works without these**:
  items 6, 7, 8, 9. These four together are the minimum for
  `toolchain create` to produce an out-of-the-box runnable
  Kivy 3.0 + ANGLE iOS app.
* **P1 — install/UX hygiene, real bugs but with workarounds**:
  items 10, 11, 12, 14.
* **P2 — architectural cleanup, low blast radius once SDL2 is
  dropped**: items 13, 15.

**Comment by misl6** [comment]
The build process for Kivy in kivy-ios was largely abandoned and has since been streamlined into kivy/kivy. What we actually need to do in kivy-ios is add tooling to download (and build) Python3.framework, as described in the Python docs,  along with project creation and scaffolding helpers.

This is doable manually (it's what I'm currently running for my own deployments), but moving it into a proper automated tool is clearly the better approach. I've never had the time to tackle it, but I'm open to doing so.

Beyond building Python3.framework and its dependencies, the process is fairly straightforward as only minor changes to our current template are needed.

If you're interested in helping make this clean and usable, I can put together a small demo script over the next week.

**Comment by ElliotGarbus** [comment]
I'd be happy to help.  

I'm currently working on https://github.com/kivy/kivy/pull/9314 to use the Apple AVFoundation as a video provider for macOS and IOS.  The macOS version is working, I hit all of these issues trying to build for IOS.  I expect to have #9314 done in the next few days.

**Comment by kengoon** [comment]
> The build process for Kivy in kivy-ios was largely abandoned and has since been streamlined into kivy/kivy. What we actually need to do in kivy-ios is add tooling to download (and build) Python3.framework, as described in the Python docs, along with project creation and scaffolding helpers.
> 
> This is doable manually (it's what I'm currently running for my own deployments), but moving it into a proper automated tool is clearly the better approach. I've never had the time to tackle it, but I'm open to doing so.
> 
> Beyond building Python3.framework and its dependencies, the process is fairly straightforward as only minor changes to our current template are needed.
> 
> If you're interested in helping make this clean and usable, I can put together a small demo script over the next week.

@misl6 can you expand on. how do you build Python3.framework

**Comment by ElliotGarbus** [comment]
@kengoon 
I don't know if this helps.  I built wheels for kivy, pyinius and pyobjus for kivyforge development.
The wheel building site: https://github.com/ElliotGarbus/kivy-mobile-wheels
The wheels: https://elliotgarbus.github.io/kivy-mobile-wheels/ click browse index to see what is available.  

Note the IOS work is limited to kivy 3.0 and a pre-release version of Python 3.15.  Python ver 3.15 has an official release scheduled for Oct.
Here is kivyforge, https://github.com/ElliotGarbus/kivyforge a build tool that will build for all kivy supported platforms.  Still a WIP but up and running.

**Comment by kengoon** [comment]
@ElliotGarbus Thank you so much, I needed that upgrade due to third-party spm package that I'm working with (firebase). 

Also one more thing, do you think beeware rubicon [`@Block`](https://rubicon-objc.beeware.org/en/latest/reference/rubicon-objc-api/?h=%40blo#rubicon.objc.api.Block) handler will work well with python3.15 that kivyforge builds? It works on python3.11 on mac and freezes on iOS with lldb pointing towards this `ffi_call_SYSV (context, frame, fn, rvalue, flags, closure);
Thread 1: EXC_BAD_ACCESS (code=1, address=0x0)`. I'm trying to avoid too many objective-c .m file code with pyobjus because pyobjus only supports `@protocol` which I use to call python from objectivec-c while beeware rubicon allows me to write code solely in python if I want to.

Please if you have any information that could help me, I would appreciate it. In the meantime, I will test what you gave me.

**Comment by ElliotGarbus** [comment]
@kengoon 
I have not done anything with Rubicon, but that seems like a good question for the Beeware team.  I'm using Python 3.15 - because it is the first python to officially support IOS.  

It looks like the bug you are describing is a bug in the libffi.  I would hope Python 3.15 has fixed this issue - but I don't know.

**Comment by kengoon** [comment]
@ElliotGarbus alright will do that

**Comment by ElliotGarbus** [comment]
@kengoon You might also want to look at https://github.com/ElliotGarbus/native-integration.   This is my spec for how a python package describes what it needs from the app build.  I will be integrating this into kivyforge immediately after the first release.

**Comment by kengoon** [comment]
@ElliotGarbus yeah, seen your post of it on discord. I've not got enough time to go through it in the past, just skimmed through. Seems now's a good time to have a proper read of it.
